import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "../components/header";
import Login from "../components/login";
import styles from "../styles/Home.module.scss";
import cover from "../assets/images/cover.png";
import { Router, useRouter } from "next/router";

export default function Home() {
  const route = useRouter();
  const handleroute = () => {
    if (localStorage.getItem("Token") && localStorage.getItem("Role")) {
      if (localStorage.getItem("Role") === "admin") {
        route.push("employee-admin");
      }
    } else {
      route.push("login");
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>EC Reports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://kit.fontawesome.com/13bd9064b7.js"
          crossorigin="anonymous"
          async
        />
      </Head>
      <div className={styles.banner}>
        <Header logoWhite />
        <div className={styles.banner_content}>
          <div className={styles.left}>
            <div className={styles.content}>
              <div className={styles.sub_title}>GO PAPERLESS TODAY</div>
              <div className={styles.title}>
                Web-based Multi-Inspection Reporting Application Completely
                Paperless, Offline and online mode.
              </div>
              <div className={styles.description}>
                Distribute data’s in your templates EC Reports will help to
                complete your work reports in fast track.
              </div>
              <button onClick={handleroute}>
                <a>Login</a>
              </button>
            </div>
          </div>
          <div className={styles.right}>
            <Image src={cover} alt="EC Reports" width={400} height={400} />
          </div>
        </div>
      </div>
    </div>
  );
}
